package hackathon;

import java.awt.Color;
import javax.swing.JOptionPane;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author adamchen
 */
public class frame extends javax.swing.JFrame {

    //variables
    int route = 0;
    int ride = 0;
    static int carCount = 0;
    static int busCount = 0;
    static int motoCount = 0;
    static int peopleLeft; 
    static int time = 0;
    static int CO2 = 0;
    static int peopleStart;
    final int xCord = 240;
    final int yCord = 425;
    
    
    /**
     * Creates new form frame
     */
    public frame() {
        
        initComponents();
        pp.setBackground(new Color(0, 0, 0, 0));
        listp.setVisible(false);
        car.setVisible(false);
        moto.setVisible(false);
        bus.setVisible(false);
        peopleLeft = (int)(Math.random()*35)+45;
        peopleStart = peopleLeft;
        housePplCount.setText("" + peopleLeft);
        timeTakenCount.setText("" + time);
        CO2EmissionCount.setText("" + CO2);
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        house = new javax.swing.JLabel();
        market = new javax.swing.JLabel();
        btnblue = new javax.swing.JButton();
        btngreen = new javax.swing.JButton();
        btnpurp = new javax.swing.JButton();
        pp = new javax.swing.JPanel();
        blue1 = new javax.swing.JLabel();
        blue3 = new javax.swing.JLabel();
        green1 = new javax.swing.JLabel();
        green2 = new javax.swing.JLabel();
        green3 = new javax.swing.JLabel();
        purp1 = new javax.swing.JLabel();
        purp4 = new javax.swing.JLabel();
        purp2 = new javax.swing.JLabel();
        blue2 = new javax.swing.JLabel();
        purp3 = new javax.swing.JLabel();
        green4 = new javax.swing.JLabel();
        listp = new javax.swing.JPanel();
        carP = new javax.swing.JPanel();
        btnMoto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        busP = new javax.swing.JPanel();
        btnBus = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        motoP = new javax.swing.JPanel();
        btnCar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        car = new javax.swing.JLabel();
        bus = new javax.swing.JLabel();
        moto = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        housePplCount = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        CO2EmissionCount = new javax.swing.JLabel();
        timeTakenCount = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        map1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(250, 200, 0, 0));
        setForeground(java.awt.Color.lightGray);
        setPreferredSize(new java.awt.Dimension(1150, 600));
        getContentPane().setLayout(null);

        house.setBackground(new java.awt.Color(204, 204, 255));
        house.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        house.setForeground(new java.awt.Color(102, 102, 255));
        house.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        house.setText("House");
        house.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        house.setOpaque(true);
        getContentPane().add(house);
        house.setBounds(300, 390, 90, 30);

        market.setBackground(new java.awt.Color(204, 204, 255));
        market.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        market.setForeground(new java.awt.Color(102, 102, 255));
        market.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        market.setText("Market");
        market.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        market.setOpaque(true);
        getContentPane().add(market);
        market.setBounds(680, 50, 90, 30);

        btnblue.setText("Route 1");
        btnblue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnblueActionPerformed(evt);
            }
        });
        getContentPane().add(btnblue);
        btnblue.setBounds(470, 490, 97, 29);

        btngreen.setText("Route 2");
        btngreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngreenActionPerformed(evt);
            }
        });
        getContentPane().add(btngreen);
        btngreen.setBounds(370, 350, 97, 29);

        btnpurp.setText("Route 3");
        btnpurp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpurpActionPerformed(evt);
            }
        });
        getContentPane().add(btnpurp);
        btnpurp.setBounds(250, 40, 97, 29);

        blue1.setBackground(new java.awt.Color(102, 255, 255));
        blue1.setFont(new java.awt.Font("Lucida Grande", 1, 70)); // NOI18N
        blue1.setForeground(new java.awt.Color(102, 255, 255));
        blue1.setText("_______________");
        blue1.setOpaque(true);

        blue3.setBackground(new java.awt.Color(102, 255, 255));
        blue3.setFont(new java.awt.Font("Lucida Grande", 1, 70)); // NOI18N
        blue3.setForeground(new java.awt.Color(102, 255, 255));
        blue3.setText("_______________");
        blue3.setOpaque(true);

        green1.setBackground(new java.awt.Color(153, 255, 153));
        green1.setFont(new java.awt.Font("Lucida Grande", 1, 70)); // NOI18N
        green1.setForeground(new java.awt.Color(153, 255, 153));
        green1.setText("_______________");
        green1.setOpaque(true);

        green2.setBackground(new java.awt.Color(153, 255, 153));
        green2.setFont(new java.awt.Font("Lucida Grande", 1, 70)); // NOI18N
        green2.setForeground(new java.awt.Color(153, 255, 153));
        green2.setText("_______________");
        green2.setOpaque(true);

        green3.setBackground(new java.awt.Color(153, 255, 153));
        green3.setFont(new java.awt.Font("Lucida Grande", 1, 70)); // NOI18N
        green3.setForeground(new java.awt.Color(153, 255, 153));
        green3.setText("_______________");
        green3.setOpaque(true);

        purp1.setBackground(new java.awt.Color(153, 153, 255));
        purp1.setFont(new java.awt.Font("Lucida Grande", 1, 70)); // NOI18N
        purp1.setForeground(new java.awt.Color(153, 153, 255));
        purp1.setText("_______________");
        purp1.setOpaque(true);

        purp4.setBackground(new java.awt.Color(153, 153, 255));
        purp4.setFont(new java.awt.Font("Lucida Grande", 1, 70)); // NOI18N
        purp4.setForeground(new java.awt.Color(153, 153, 255));
        purp4.setText("_______________");
        purp4.setOpaque(true);

        purp2.setBackground(new java.awt.Color(153, 153, 255));
        purp2.setFont(new java.awt.Font("Lucida Grande", 1, 70)); // NOI18N
        purp2.setForeground(new java.awt.Color(153, 153, 255));
        purp2.setText("_______________");
        purp2.setOpaque(true);

        blue2.setBackground(new java.awt.Color(102, 255, 255));
        blue2.setFont(new java.awt.Font("Lucida Grande", 1, 70)); // NOI18N
        blue2.setForeground(new java.awt.Color(102, 255, 255));
        blue2.setText("_______________");
        blue2.setOpaque(true);

        purp3.setBackground(new java.awt.Color(153, 153, 255));
        purp3.setFont(new java.awt.Font("Lucida Grande", 1, 70)); // NOI18N
        purp3.setForeground(new java.awt.Color(153, 153, 255));
        purp3.setText("_______________");
        purp3.setOpaque(true);

        green4.setBackground(new java.awt.Color(153, 255, 153));
        green4.setFont(new java.awt.Font("Lucida Grande", 1, 70)); // NOI18N
        green4.setForeground(new java.awt.Color(153, 255, 153));
        green4.setText("_______________");
        green4.setOpaque(true);

        javax.swing.GroupLayout ppLayout = new javax.swing.GroupLayout(pp);
        pp.setLayout(ppLayout);
        ppLayout.setHorizontalGroup(
            ppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
            .addGroup(ppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ppLayout.createSequentialGroup()
                    .addGap(0, 75, Short.MAX_VALUE)
                    .addGroup(ppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ppLayout.createSequentialGroup()
                            .addGroup(ppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(purp3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(purp2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(ppLayout.createSequentialGroup()
                                    .addGap(310, 310, 310)
                                    .addComponent(green3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(green4, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(green2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(ppLayout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(blue1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(ppLayout.createSequentialGroup()
                                    .addGap(310, 310, 310)
                                    .addComponent(purp1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(ppLayout.createSequentialGroup()
                                    .addGap(310, 310, 310)
                                    .addComponent(green1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(ppLayout.createSequentialGroup()
                                    .addGap(530, 530, 530)
                                    .addComponent(blue3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(ppLayout.createSequentialGroup()
                            .addGap(180, 180, 180)
                            .addComponent(blue2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ppLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(purp4, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 75, Short.MAX_VALUE)))
        );
        ppLayout.setVerticalGroup(
            ppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
            .addGroup(ppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ppLayout.createSequentialGroup()
                    .addGap(0, 30, Short.MAX_VALUE)
                    .addGroup(ppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ppLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(ppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(purp3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(ppLayout.createSequentialGroup()
                                    .addGap(300, 300, 300)
                                    .addComponent(purp2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(ppLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(ppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(ppLayout.createSequentialGroup()
                                    .addGap(180, 180, 180)
                                    .addComponent(green3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(100, 100, 100)
                                    .addComponent(green4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(ppLayout.createSequentialGroup()
                                    .addGap(300, 300, 300)
                                    .addComponent(green2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(ppLayout.createSequentialGroup()
                                    .addGap(440, 440, 440)
                                    .addComponent(blue1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(purp1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(ppLayout.createSequentialGroup()
                                    .addGap(180, 180, 180)
                                    .addComponent(green1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(ppLayout.createSequentialGroup()
                                    .addGap(80, 80, 80)
                                    .addComponent(blue3, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(ppLayout.createSequentialGroup()
                            .addGap(390, 390, 390)
                            .addComponent(blue2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(purp4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 30, Short.MAX_VALUE)))
        );

        getContentPane().add(pp);
        pp.setBounds(0, 10, 880, 530);

        btnMoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/moto.png"))); // NOI18N
        btnMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMotoActionPerformed(evt);
            }
        });

        jLabel1.setText("CO2: 350");

        jLabel2.setText("Speed: 2");

        jLabel3.setText("Capacity: 2");

        javax.swing.GroupLayout carPLayout = new javax.swing.GroupLayout(carP);
        carP.setLayout(carPLayout);
        carPLayout.setHorizontalGroup(
            carPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(carPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMoto)
                .addGap(0, 94, Short.MAX_VALUE))
        );
        carPLayout.setVerticalGroup(
            carPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carPLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(carPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMoto)
                    .addGroup(carPLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addGap(21, 21, 21))
        );

        btnBus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bus.png"))); // NOI18N
        btnBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusActionPerformed(evt);
            }
        });

        jLabel5.setText("Speed: 1");

        jLabel6.setText("Capacity: 20");

        jLabel4.setText("CO2: 800");

        javax.swing.GroupLayout busPLayout = new javax.swing.GroupLayout(busP);
        busP.setLayout(busPLayout);
        busPLayout.setHorizontalGroup(
            busPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(busPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(busPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBus)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        busPLayout.setVerticalGroup(
            busPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(busPLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(busPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(busPLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addComponent(btnBus))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btnCar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/carPic.png"))); // NOI18N
        btnCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarActionPerformed(evt);
            }
        });

        jLabel8.setText("CO2: 400");

        jLabel7.setText("Capacity: 4");

        jLabel9.setText("Speed: 3");

        javax.swing.GroupLayout motoPLayout = new javax.swing.GroupLayout(motoP);
        motoP.setLayout(motoPLayout);
        motoPLayout.setHorizontalGroup(
            motoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(motoPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(motoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCar)
                .addContainerGap(324, Short.MAX_VALUE))
        );
        motoPLayout.setVerticalGroup(
            motoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(motoPLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(motoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(motoPLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addComponent(btnCar))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout listpLayout = new javax.swing.GroupLayout(listp);
        listp.setLayout(listpLayout);
        listpLayout.setHorizontalGroup(
            listpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listpLayout.createSequentialGroup()
                .addGroup(listpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(motoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(busP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        listpLayout.setVerticalGroup(
            listpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(motoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(busP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(carP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(listp);
        listp.setBounds(890, 20, 160, 340);

        car.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/output-onlinepngtools.png"))); // NOI18N
        getContentPane().add(car);
        car.setBounds(1090, 120, 40, 30);

        bus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/busSide.png"))); // NOI18N
        getContentPane().add(bus);
        bus.setBounds(1090, 60, 40, 30);

        moto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/motoSide.png"))); // NOI18N
        getContentPane().add(moto);
        moto.setBounds(1090, 10, 70, 40);

        jLabel10.setBackground(new java.awt.Color(204, 204, 255));
        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 255));
        jLabel10.setText("People Left At House:");
        jLabel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(890, 380, 200, 60);

        housePplCount.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        housePplCount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        housePplCount.setText("40");
        getContentPane().add(housePplCount);
        housePplCount.setBounds(1060, 380, 70, 60);

        jLabel11.setText("Total CO2 Emission:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(950, 450, 130, 30);

        CO2EmissionCount.setText("1000");
        getContentPane().add(CO2EmissionCount);
        CO2EmissionCount.setBounds(1090, 450, 53, 30);

        timeTakenCount.setText("1000");
        getContentPane().add(timeTakenCount);
        timeTakenCount.setBounds(1090, 480, 53, 30);

        jLabel14.setText("Total Time Taken:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(950, 480, 130, 30);

        map1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/map1.png"))); // NOI18N
        getContentPane().add(map1);
        map1.setBounds(1, 6, 877, 538);

        getAccessibleContext().setAccessibleName("jframe");
        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarActionPerformed
       ride = 1;
       carCount++;
       car.setVisible(true);
       car.setLocation(xCord, yCord);
       btnCar.setVisible(false);
       if (route == 1){
           blueRide();
       }else if (route == 2){
           greenRide();
       }else{
           purpRide();
       }
       updatePplLeft();
    }//GEN-LAST:event_btnCarActionPerformed

    private void btnpurpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpurpActionPerformed
        route = 3;
        btnblue.setVisible(false);
        btngreen.setVisible(false);
        btnpurp.setVisible(false);
        pp.setVisible(false);
        listp.setVisible(true);
        JOptionPane.showMessageDialog(null, "Then begin to make your combinations of vehicles!");
    }//GEN-LAST:event_btnpurpActionPerformed

    private void btngreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngreenActionPerformed
        route = 2;
        btnpurp.setVisible(false);
        btnblue.setVisible(false);
        btngreen.setVisible(false);
        pp.setVisible(false);
        listp.setVisible(true);
        JOptionPane.showMessageDialog(null, "Then begin to make your combinations of vehicles!");
    }//GEN-LAST:event_btngreenActionPerformed

    private void btnblueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnblueActionPerformed
        route = 1;
        btnpurp.setVisible(false);
        btngreen.setVisible(false);
        btnblue.setVisible(false);
        pp.setVisible(false);
        listp.setVisible(true);
        JOptionPane.showMessageDialog(null, "Then begin to make your combinations of vehicles!");
    }//GEN-LAST:event_btnblueActionPerformed

    private void btnMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMotoActionPerformed
       ride = 2;
       motoCount++;
       moto.setVisible(true);
       moto.setLocation(xCord, yCord);
       btnMoto.setVisible(false);
       if (route == 1){
           blueRide();
       }else if (route == 2){
           greenRide();
       }else{
           purpRide();
       }
       updatePplLeft();
    }//GEN-LAST:event_btnMotoActionPerformed

    private void btnBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusActionPerformed
       ride = 3;
       busCount++;
       bus.setVisible(true);
       bus.setLocation(xCord, yCord);
       btnBus.setVisible(false);
       if (route == 1){
           blueRide();
       }else if (route == 2){
           greenRide();
       }else{
           purpRide();
       }
       updatePplLeft();
    }//GEN-LAST:event_btnBusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            
            }
        });
        
        
    }
    
    public void blueRide(){
        Thread animation = new Thread(new Runnable() {
           @Override
           public void run() {
             
               int x = xCord;
               int y = yCord;
               
               if (ride == 1){
                    while (y < 486){
                        car.setLocation(x, y);
                        y += 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }

                    while (x < 780){
                        car.setLocation(x, y);
                        x += 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }

                    while (y > 150){
                        car.setLocation(x, y);
                        y -= 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }

                    car.setVisible(false);
                    btnCar.setVisible(true);
               }
               
               else if(ride == 2){
                   while (y < 486){
                        moto.setLocation(x, y);
                        y += 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }

                    while (x < 780){
                        moto.setLocation(x, y);
                        x += 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }

                    while (y > 150){
                        moto.setLocation(x, y);
                        y -= 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }

                    moto.setVisible(false);
                    btnMoto.setVisible(true);
               }
               
               else {
                   while (y < 486){
                        bus.setLocation(x, y);
                        y += 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }

                    while (x < 780){
                        bus.setLocation(x, y);
                        x += 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }

                    while (y > 150){
                        bus.setLocation(x, y);
                        y -= 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }

                    bus.setVisible(false);
                    btnBus.setVisible(true);
               }
               
               
               
           }
       });
        
       animation.start();
       
    }

    public void greenRide(){
        Thread animation = new Thread(new Runnable() {
           @Override
           public void run() {
             
               int x = xCord;
               int y = yCord;
               
               if (ride == 1){
                    while (y > 350){
                        car.setLocation(x, y);
                        y -= 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }

                    while (x < 555){
                        car.setLocation(x, y);
                        x += 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }

                    while (y > 220){
                        car.setLocation(x, y);
                        y -= 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }
                    
                    while (x < 780){
                        car.setLocation(x, y);
                        x += 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }

                    while (y > 150){
                        car.setLocation(x, y);
                        y -= 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }
                    
                    car.setVisible(false);
                    btnCar.setVisible(true);
               }
               
               else if(ride == 2){
                   while (y > 350){
                        moto.setLocation(x, y);
                        y -= 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }

                    while (x < 555){
                        moto.setLocation(x, y);
                        x += 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }

                    while (y > 220){
                        moto.setLocation(x, y);
                        y -= 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }
                    
                    while (x < 780){
                        moto.setLocation(x, y);
                        x += 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }

                    while (y > 150){
                        moto.setLocation(x, y);
                        y -= 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }
                    
                    moto.setVisible(false);
                    btnMoto.setVisible(true);
               }
               
               else {
                   while (y > 350){
                        bus.setLocation(x, y);
                        y -= 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }

                    while (x < 555){
                        bus.setLocation(x, y);
                        x += 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }

                    while (y > 220){
                        bus.setLocation(x, y);
                        y -= 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }
                    
                    while (x < 780){
                        bus.setLocation(x, y);
                        x += 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }

                    while (y > 150){
                        bus.setLocation(x, y);
                        y -= 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }
                    
                    bus.setVisible(false);
                    btnBus.setVisible(true);
               }
               
               
               
           }
       });
        
       animation.start();
       
    }
    
    public void purpRide(){
        Thread animation = new Thread(new Runnable() {
           @Override
           public void run() {
             
               int x = xCord;
               int y = yCord;
               
               if (ride == 1){
                    while (y > 350){
                        car.setLocation(x, y);
                        y -= 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }

                    while (x > 60){
                        car.setLocation(x, y);
                        x -= 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }

                    while (y > 30){
                        car.setLocation(x, y);
                        y -= 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }
                    
                    while (x < 550){
                        car.setLocation(x, y);
                        x += 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }

                    while (y < 220){
                        car.setLocation(x, y);
                        y += 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }
                    
                    while (x < 780){
                        car.setLocation(x, y);
                        x += 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }

                    while (y > 150){
                        car.setLocation(x, y);
                        y -= 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }
                    
                    car.setVisible(false);
                    btnCar.setVisible(true);
               }
               
               else if(ride == 2){
                   while (y > 350){
                        moto.setLocation(x, y);
                        y -= 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }

                    while (x > 60){
                        moto.setLocation(x, y);
                        x -= 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }

                    while (y > 30){
                        moto.setLocation(x, y);
                        y -= 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }
                    
                    while (x < 550){
                        moto.setLocation(x, y);
                        x += 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }

                    while (y < 220){
                        moto.setLocation(x, y);
                        y += 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }
                    
                    while (x < 780){
                        moto.setLocation(x, y);
                        x += 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }

                    while (y > 150){
                        moto.setLocation(x, y);
                        y -= 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }
                    
                    moto.setVisible(false);
                    btnMoto.setVisible(true);
               }
               
               else {
                   while (y > 350){
                        bus.setLocation(x, y);
                        y -= 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }

                    while (x > 60){
                        bus.setLocation(x, y);
                        x -= 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }

                    while (y > 30){
                        bus.setLocation(x, y);
                        y -= 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }
                    
                    while (x < 550){
                        bus.setLocation(x, y);
                        x += 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }

                    while (y < 220){
                        bus.setLocation(x, y);
                        y += 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }
                    
                    while (x < 780){
                        bus.setLocation(x, y);
                        x += 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }

                    while (y > 150){
                        bus.setLocation(x, y);
                        y -= 5;

                        try{
                            Thread.sleep(10);
                        }catch(Exception e){ }
                    }
                    
                    bus.setVisible(false);
                    btnBus.setVisible(true);
               }
               
               
               
           }
       });
        
       animation.start();
    }
    
    public void updatePplLeft(){
        peopleLeft = peopleStart - carCount*4 - busCount*20 - motoCount *2;
        time = carCount*3 + busCount *1 + motoCount*2;
        if (route == 1){
            time = time * 18;
        }else if (route == 2){
            time = time * 10;
        }else {
            time = time * 30;
        }
        CO2 = carCount*400 + busCount*800 + motoCount*350;
        if (peopleLeft < 0){
            housePplCount.setText("0");
        }else {
            housePplCount.setText("" + peopleLeft);
        }
        timeTakenCount.setText("" + time);
        CO2EmissionCount.setText("" + CO2);
        
    }
    
    public int getTimeTaken(){
        return time;
    }
    
    public int getCO2(){
        return CO2;
    }
    
    public int getPeopleLeft(){
        return peopleLeft;
    }
    
    public int getRideCount(){
        return (carCount + busCount + motoCount);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel CO2EmissionCount;
    private javax.swing.JLabel blue1;
    private javax.swing.JLabel blue2;
    private javax.swing.JLabel blue3;
    private javax.swing.JButton btnBus;
    private javax.swing.JButton btnCar;
    private javax.swing.JButton btnMoto;
    private javax.swing.JButton btnblue;
    private javax.swing.JButton btngreen;
    private javax.swing.JButton btnpurp;
    private javax.swing.JLabel bus;
    private javax.swing.JPanel busP;
    private javax.swing.JLabel car;
    private javax.swing.JPanel carP;
    private javax.swing.JLabel green1;
    private javax.swing.JLabel green2;
    private javax.swing.JLabel green3;
    private javax.swing.JLabel green4;
    private javax.swing.JLabel house;
    private static javax.swing.JLabel housePplCount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel listp;
    private javax.swing.JLabel map1;
    private javax.swing.JLabel market;
    private javax.swing.JLabel moto;
    private javax.swing.JPanel motoP;
    private javax.swing.JPanel pp;
    private javax.swing.JLabel purp1;
    private javax.swing.JLabel purp2;
    private javax.swing.JLabel purp3;
    private javax.swing.JLabel purp4;
    private static javax.swing.JLabel timeTakenCount;
    // End of variables declaration//GEN-END:variables
}
